version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Essential linters for Go best practices
    - bodyclose          # HTTP response body closure
    - dupl               # Duplicate code detection
    - errcheck           # Unchecked errors
    - govet              # Go vet checks
    - ineffassign        # Ineffectual assignments
    - staticcheck        # Staticcheck SA checks (includes gosimple)
    - unused             # Unused code detection
    
    # Code quality and style
    - gochecknoinits     # No init functions
    - goconst            # Repeated strings to constants
    - gocritic           # Various diagnostics with auto-fix
    - gocyclo            # Cyclomatic complexity
    - gosec              # Security issues
    - misspell           # Spelling mistakes with auto-fix
    - unconvert          # Unnecessary type conversions
    - unparam            # Unused parameters
    - whitespace         # Unnecessary whitespace with auto-fix
    
    # Additional valuable linters
    - errorlint          # Error wrapping issues with auto-fix
    - revive             # Fast, configurable replacement for golint
    - predeclared        # Shadowing of predeclared identifiers
    - nolintlint         # Proper nolint directives with auto-fix
    
    # Performance and best practices
    - prealloc           # Slice preallocation
    - rowserrcheck       # SQL rows.Err() checking
    - sqlclosecheck      # SQL close checking
    - copyloopvar        # Loop variable copying with auto-fix
    - perfsprint         # fmt.Sprintf performance with auto-fix
    
    # Code style improvements
    - godot              # Comments ending with period with auto-fix
    - nlreturn           # Newlines before returns with auto-fix
    - bidichk            # Dangerous unicode character sequences
    - asciicheck         # Non-ASCII identifiers
    - usestdlibvars      # Use standard library variables/constants

  exclusions:
    generated: lax  # Maintain v1 behavior
    paths:
      - vendor
      - dist
      - ".*_test.go"
    rules:
      # Exclude some linters from running on tests files.
      - path: "_test\\.go"
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
          - gocritic
          - revive
          - gofumpt
      # Exclude known linters from partially hard-to-fix issues
      - linters:
          - staticcheck
        text: "ST1003:"
      - linters:
          - staticcheck
        text: "should be"
      - linters:
          - revive
        text: "exported:"
      # Allow longer lines in generated code and configuration
      - path: ".*\\.pb\\.go"
        linters:
          - lll
      # Allow init functions in main package
      - path: "cmd/"
        linters:
          - gochecknoinits
      # Integer conversions in audio processing are safe
      - path: "pkg/audio/"
        linters:
          - gosec
        text: "G115"
      # WAV file creation is internal debug functionality
      - path: "internal/voice/debug.go"
        linters:
          - gosec
        text: "G304|G115"

  settings:
    gocyclo:
      min-complexity: 25  # Increased for complex audio processing functions
    dupl:
      threshold: 100
    goconst:
      min-len: 3          # Increased from 2 to avoid false positives
      min-occurrences: 3  # Increased from 2 for more meaningful constants
    misspell:
      locale: US
    lll:
      line-length: 140    # Increased from 120 for modern Go development
    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK
        - TODO              # Added TODO back as it's commonly used
        - FIXME             # Added FIXME for critical issues
    funlen:
      lines: 100          # Increased from 80 for more realistic limits
      statements: 60      # Increased from 50 for more realistic limits
    govet:
      enable:
        - shadow
        - printf
        - shift
        - structtag
        - unreachable
    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: indent-error-flow
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - appendAssign     # This can be overly strict in some cases
        - sloppyReassign   # Style preference, not an error
        - hugeParam        # Interface constraints make pointer passing complex

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/Raikerian/go-discord-chatgpt

output:
  formats:
    text:
      colors: true
      print-issued-lines: true
      print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
