version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  exclusions:
    generated: lax  # Maintain v1 behavior
    paths:
      - vendor
      - dist
      - ".*_test.go"
    rules:
      # Exclude some linters from running on tests files.
      - path: "_test\\.go"
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
      # Exclude known linters from partially hard-to-fix issues
      - linters:
          - staticcheck
        text: "ST1003:"
      - linters:
          - staticcheck
        text: "should be"

  settings:
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 120
    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK
    funlen:
      lines: 80
      statements: 50
    govet:
      enable:
        - shadow  # Replaces check-shadowing: true

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/Raikerian/go-discord-chatgpt

output:
  formats:
    text:
      colors: true
      print-issued-lines: true
      print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
