dir: pkg/test
filename: "mock_{{.InterfaceName | snakecase}}.go"
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: test
packages:
  github.com/Raikerian/go-discord-chatgpt/internal/commands:
    interfaces:
      Command:
  github.com/Raikerian/go-discord-chatgpt/pkg/openai:
    interfaces:
      PricingService:
  github.com/Raikerian/go-discord-chatgpt/internal/voice:
    interfaces:
      AudioMixer:
